// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "timble/module/users/entity"

	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, params
func (_m *AuthUsecase) Login(ctx context.Context, params entity.UserLoginParams) (entity.UserToken, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 entity.UserToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserLoginParams) (entity.UserToken, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserLoginParams) entity.UserToken); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(entity.UserToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserLoginParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
