// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// UsersRESTInterface is an autogenerated mock type for the UsersRESTInterface type
type UsersRESTInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GrantPremium provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) GrantPremium(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Login provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) Login(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// React provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) React(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Show provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) Show(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UnsubscribePremium provides a mock function with given fields: w, r
func (_m *UsersRESTInterface) UnsubscribePremium(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewUsersRESTInterface creates a new instance of UsersRESTInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersRESTInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersRESTInterface {
	mock := &UsersRESTInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
